gallery/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'gallery.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('photo.urls', namespace='photo'))
)

photo/urls.py
from django.conf import settings

__author__ = 'ashchuk'

from django.conf.urls import patterns, url
from photo import views
urlpatterns = patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^$', views.IndexView.as_view(), name='index'),
    # url(r'^category/(?P<pk>\d+)$', views.AlbumsView.as_view(), name='category'),
    url(r'^albums/(?P<pk>\d+)$', views.PhotoView.as_view(), name='albums'),
    url(r'^thanks/$', views.thanks, name='thanks'),
    url(r'^error/$', views.error, name='error'),
    url(r'^feedback/$', views.feedback, name='feedback'),
)

photo/models.py
# coding=utf-8
from django.db import models
from sorl.thumbnail import ImageField
from django.utils import timezone

'''
# It's a category class
# Use it, then need division into albums

class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    category_thumbnail = ImageField(upload_to='category_thumbnails')

    def __unicode__(self):
        return self.name
'''


class Album(models.Model):
    # Here's a category-album relation
    #
    # category = models.ForeignKey(Category)
    #

    name = models.CharField(max_length=100)
    description = models.TextField()
    pub_date = models.DateTimeField('Publishing date', default=timezone.now())
    album_thumbnail = ImageField(upload_to='album_thumbnails')

    def __unicode__(self):
        return self.name


class Photo(models.Model):
    album = models.ForeignKey(Album)
    title = models.CharField(max_length=100)
    image = ImageField(upload_to='photos')
    caption = models.CharField(max_length=250, blank=True)
    pub_date = models.DateTimeField('Publishing date', default=timezone.now())

    def __unicode__(self):
        return self.title


class Feedback(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    pub_date = models.DateTimeField('Publishing date', default=timezone.now())
    message = models.TextField()

    def __unicode__(self):
        return self.name

photo/forms.py
# coding=utf-8
__author__ = 'ashchuk'

from django import forms
from nocaptcha_recaptcha import NoReCaptchaField


class ReCaptchaForm(forms.Form):
    name = forms.CharField(
            label='Your name',
            required=True,
            widget=forms.TextInput(
                    attrs={'class': 'validate[required] text-input',
                           'type': "text", 'name': "name", 'id': "name", 'placeholder': "Имя"}))
    subject = forms.CharField(
            label='Your subject',
            required=True,
            widget=forms.TextInput(
                    attrs={'class': 'validate[required] text-input',
                           'type': "text", 'name': "subject", 'id': "subject", 'placeholder': "Заголовок"}))
    email = forms.EmailField(
            label='Your e-mail address',
            required=True,
            widget=forms.TextInput(attrs={'class': 'validate[required,custom[email]] text-input',
                                          'type': "text", 'name': "email", 'id': "email", 'placeholder': "Электронная почта"}))
    message = forms.CharField(
            label='Your message',
            required=True,
            widget=forms.Textarea(attrs={'class': 'validate[required] text-input',
                                         'type': "text", 'name': "message", 'id': "message", 'placeholder': "Текст сообщения"}))
    recaptcha = NoReCaptchaField(gtag_attrs={'data-theme':'dark'})

photo/views.py
    # -*- coding: utf-8 -*-
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.utils import timezone
from gallery import settings
from photo.forms import ReCaptchaForm
from photo.models import Album, Feedback
from django.views import generic
from django.views.decorators.csrf import csrf_protect
from smtplib import SMTPException


@csrf_protect
def feedback(request):
    print('request GET ' + str(request.path))
    if request.method == 'POST':
        form = ReCaptchaForm(request.POST)
        if form.is_valid():
            feed = form.cleaned_data
            try:
                new_feedback = Feedback()
                typed_name = feed['name']
                typed_email = request.POST['email']
                typed_message = request.POST['message']
                typed_subject = request.POST['subject']
            except KeyError:
                return HttpResponseRedirect(reverse('photo:error'))
            else:
                new_feedback.name = typed_name
                new_feedback.email = typed_email
                new_feedback.message = typed_message
                new_feedback.subject = typed_subject
                new_feedback.save()
                print('Saved')
                try:
                    subject = feed['subject']
                    message = typed_name + '\n' + typed_email + '\n' + typed_message + '\n' + typed_subject
                    from_email = settings.EMAIL_HOST_USER
                    to_list = [typed_email]
                    send_mail(subject, message, from_email, to_list, fail_silently=False)
                except SMTPException:
                    return HttpResponseRedirect(reverse('photo:error'))
                else:
                    pass
            return HttpResponseRedirect(reverse('photo:thanks'))
        else:
            return HttpResponseRedirect(reverse('photo:error'))


def thanks(request):
    return render_to_response('photo/thanks.html')


def error(request):
    return render_to_response('photo/error.html')


class IndexView(generic.ListView):
    template_name = 'photo/index.html'
    context_object_name = 'albums'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Album.objects.order_by('pub_date')

    def get_context_data(self, **kwargs):
        form = ReCaptchaForm()
        return {'albums': Album.objects.order_by('pub_date'), 'form': form}


'''
# Here's a category-album relation view

class AlbumsView(generic.DetailView):
    model = Category
    template_name = 'photo/albums.html'

    def get_queryset(self):
        """
        Return albums in selected category
        """
        return Category.objects.order_by('name')

    def get_context_data(self, **kwargs):
        form = ReCaptchaForm()
        return {'category': kwargs.get('object'), 'form': form}
'''


class PhotoView(generic.DetailView):
    model = Album
    template_name = 'photo/photos.html'
    def get_queryset(self):
        """
        Return photos in selected album
        """
        return Album.objects.filter(pub_date__lte=timezone.now())

    def get_context_data(self, **kwargs):
        form = ReCaptchaForm()
        return {'album': kwargs.get('object'), 'form': form}

photo/templates/photo/albums.html
<!DOCTYPE HTML>
<!--
	Miniport by HTML5 UP
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
{% load staticfiles %}
{% load thumbnail %}

        <!--[if lte IE 8]><script src="{% static 'photo/css/ie/html5shiv.js' %}"></script><![endif]-->
<script src="{% static 'photo/js/jquery.min.js' %}"></script>
<script src="{% static 'photo/js/skel.min.js' %}"></script>
<script src="{% static 'photo/js/jquery.scrolly.min.js' %}"></script>
<script src="{% static 'photo/js/init.js' %}"></script>

<link rel="stylesheet" type="text/css" href="{% static 'photo/css/skel.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'photo/css/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'photo/css/style-desktop.css' %}" />

        <!--[if lte IE 8]><link rel="stylesheet" href="{% static 'photo/css/ie/v8.css' %}" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="{% static 'photo/css/ie/v9.css' %}" /><![endif]-->

<head lang="en">
		<title>Фотограф Анастасия Травкина</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
	</head>
	<body>

		<!-- Nav -->
			<nav id="nav">
				<ul class="container">
                    <li><a href="http://127.0.0.1:8000/index">Home</a></li>
					<li><a href="#portfolio">Portfolio</a></li>
					<li><a href="#contact">Contact</a></li>
				</ul>
			</nav>

		<!-- Portfolio -->
			<div class="wrapper style3">
				<article id="portfolio">
					<header>
						<h2>Here’s some stuff I made recently.</h2>
						<p>Category's name: <strong>{{ category.name }}</strong></p>
                        <p>Category's description: <strong>{{ category.description }}</strong></p>
					</header>
					<div class="container">
                        <div class="row">
                            {% for album in category.album_set.all %}
							<div class="4u">
								<article class="box style2">
                                    {% thumbnail album.album_thumbnail "384x269" crop="center" as thumb %}
                                        <a href="{% url 'photo:albums' album.id %}" class="image featured"><img src="{{ thumb.url }}" width="{{ thumb.width }}" height="{{ thumb.height }}" alt="" /></a>
                                    {% endthumbnail %}
									<h3><a href="{% url 'photo:albums' album.id %}">{{ album.name }}</a></h3>
									<p>{{ album.description }}</p>
								</article>
							</div>
                            {% endfor %}
						</div>
					</div>
					<footer>
						<p>Lorem ipsum dolor sit sapien vestibulum ipsum primis?</p>
						<a href="#contact" class="button big scrolly">Get in touch with me</a>
					</footer>
				</article>
			</div>

		<!-- Contact -->
			<div class="wrapper style4">
				<article id="contact" class="container 75%">
					<header>
						<h2>Have me make stuff for you.</h2>
						<p>Ornare nulla proin odio consequat sapien vestibulum ipsum sed lorem.</p>
					</header>
					<div>
						<div class="row">
							<div class="12u">
								<form method="post" action="{% url 'photo:index' %}" id="formID">
                                    {% csrf_token %}
									<div>
										<div class="row">
											<div class="6u">
                                                {{ form.name }}
											</div>
											<div class="6u">
                                                {{ form.email }}
											</div>
										</div>
										<div class="row">
											<div class="12u">
                                                {{ form.subject }}
											</div>
										</div>
										<div class="row">
											<div class="12u">
                                                {{ form.message }}
											</div>
										</div>
										<div class="row 200%">
											<div class="12u">
												<ul class="actions">
                                                    {{ form.recaptcha.errors|join:", " }}
                                                    <br>
                                                    {{ form.recaptcha }}
                                                    <br>
                                                    <br>
													<li><input type="submit" class="submit" value="Send Message" /></li>
													<li><input type="reset" value="Clear Form" class="alt" /></li>
												</ul>
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>
						<div class="row">
							<div class="12u">
								<hr />
								<h3>Find me on ...</h3>
								<ul class="social">
									<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
									<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
									<li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
									<li><a href="#" class="icon fa-linkedin"><span class="label">LinkedIn</span></a></li>
									<li><a href="#" class="icon fa-tumblr"><span class="label">Tumblr</span></a></li>
									<li><a href="#" class="icon fa-google-plus"><span class="label">Google+</span></a></li>
									<li><a href="#" class="icon fa-github"><span class="label">Github</span></a></li>
									<!--
									<li><a href="#" class="icon fa-rss"><span>RSS</span></a></li>
									<li><a href="#" class="icon fa-instagram"><span>Instagram</span></a></li>
									<li><a href="#" class="icon fa-foursquare"><span>Foursquare</span></a></li>
									<li><a href="#" class="icon fa-skype"><span>Skype</span></a></li>
									<li><a href="#" class="icon fa-soundcloud"><span>Soundcloud</span></a></li>
									<li><a href="#" class="icon fa-youtube"><span>YouTube</span></a></li>
									<li><a href="#" class="icon fa-blogger"><span>Blogger</span></a></li>
									<li><a href="#" class="icon fa-flickr"><span>Flickr</span></a></li>
									<li><a href="#" class="icon fa-vimeo"><span>Vimeo</span></a></li>
									-->
								</ul>
								<hr />
							</div>
						</div>
					</div>
					<footer>
						<ul id="copyright">
							<li>&copy; Untitled. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
						</ul>
					</footer>
				</article>
			</div>

	</body>
</html>

photo/templates/photo/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
{% load thumbnail %}

{% block scripts %}
    <!--[if lte IE 8]><script src="{% static 'photo/css/ie/html5shiv.js' %}"></script><![endif]-->
<script src="{% static 'photo/js/jquery.min.js' %}"></script>
<script src="{% static 'photo/js/skel.min.js' %}"></script>
<script src="{% static 'photo/js/jquery.scrolly.min.js' %}"></script>
<script src="{% static 'photo/js/init.js' %}"></script>
<script src="{% static 'photo/js/jquery.validationEngine-ru.js' %}"></script>
<script src="{% static 'photo/js/jquery.validationEngine.js' %}"></script>

<script>
      jQuery(document).ready(function(){
        // binds form submission and fields to the validation engine
        jQuery("#formID").validationEngine();
      });

      /**
      *
      * @param {jqObject} the field where the validation applies
      * @param {Array[String]} validation rules for this field
      * @param {int} rule index
      * @param {Map} form options
      * @return an error string if validation failed
      */
    </script>

<link rel="stylesheet" type="text/css" href="{% static 'photo/css/skel.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'photo/css/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'photo/css/style-desktop.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'photo/css/validationEngine.jquery.css' %}" />

        <!--[if lte IE 8]><link rel="stylesheet" href="{% static 'photo/css/ie/v8.css' %}" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="{% static 'photo/css/ie/v9.css' %}" /><![endif]-->
{% endblock %}

<head lang="en">
        {% block head %}
            <title>Фотограф Анастасия Травкина</title>
            <meta http-equiv="content-type" content="text/html; charset=utf-8" />
            <meta name="description" content="" />
            <meta name="keywords" content="" />
            <link rel="icon" href="{% static 'photo/images/favicon.ico' %}" type="image/x-icon">
            <link rel="shortcut icon" href="{% static 'photo/images/favicon.ico' %}" type="image/x-icon">
            <meta charset="UTF-8">
        {% endblock %}
</head>
<body>

    {% block nav %}
        <nav id="nav">
				<ul class="container">
					<li><a href="{% url 'photo:index' %}">Главная</a></li>
				</ul>
			</nav>
    {% endblock %}

    {% block home %}
    {% endblock %}

    {% block work %}
    {% endblock %}

    {% block portfolio %}
    {% endblock %}

    {% block contact %}
        <div class="wrapper style4">
				<article id="contact" class="container 75%">
					<header>
						<h2>Напишите мне письмо.</h2>
						<p>Задавайте вопросы, я Вам обязательно отвечу.</p>
					</header>
					<div>
						<div class="row">
							<div class  ="12u">
								<form method="post" action="{% url 'photo:feedback' %}" id="formID">
                                    {% csrf_token %}
									<div>
										<div class="row">
											<div class="6u">
                                                {{ form.name }}
											</div>
											<div class="6u">
                                                {{ form.email }}
											</div>
										</div>
										<div class="row">
											<div class="12u">
                                                {{ form.subject }}
											</div>
										</div>
										<div class="row">
											<div class="12u">
                                                {{ form.message }}
											</div>
										</div>
										<div class="row 200%">
											<div class="12u">
												<ul class="actions">
                                                    {{ form.recaptcha.errors|join:", " }}
                                                    <br>
                                                    {{ form.recaptcha }}
                                                    <br>
                                                    <br>
													<li><input type="submit" class="submit" value="Отправить" /></li>
													<li><input type="reset" value="Очистить" class="alt" /></li>
												</ul>
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>
						<div class="row">
							<div class="12u">
								<hr />
								<h3>Ищите меня в социальных сетях</h3>
								<ul class="social">
									<li><a href="http://vk.com/travkina.anastasia_photo" class="icon fa-vk"><span class="label"></span></a></li>
                                    <li><a href="https://instagram.com/nastenka_kshk/" class="icon fa-instagram"><span></span></a></li>
                                    <li><a href="https://twitter.com/murkamur1995" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
									<li><a href="https://www.facebook.com/profile.php?id=100008995661742" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
									<!--
									<li><a href="#" class="icon fa-rss"><span>RSS</span></a></li>
									<li><a href="#" class="icon fa-instagram"><span>Instagram</span></a></li>
									<li><a href="#" class="icon fa-foursquare"><span>Foursquare</span></a></li>
									<li><a href="#" class="icon fa-skype"><span>Skype</span></a></li>
									<li><a href="#" class="icon fa-soundcloud"><span>Soundcloud</span></a></li>
									<li><a href="#" class="icon fa-youtube"><span>YouTube</span></a></li>
									<li><a href="#" class="icon fa-blogger"><span>Blogger</span></a></li>
									<li><a href="#" class="icon fa-flickr"><span>Flickr</span></a></li>
									<li><a href="#" class="icon fa-vimeo"><span>Vimeo</span></a></li>
									-->
								</ul>
								<hr />
							</div>
						</div>
					</div>
					<footer>
						<ul id="copyright">
							<li>&copy; 2015 Artyom Koshko. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li><li>Photo: Anastasia Travkina<li>
						</ul>
					</footer>
				</article>
			</div>
    {% endblock %}
</body>
</html>

photo/templates/photo/photos.html
<!DOCTYPE HTML>
<!--
	Miniport by HTML5 UP
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
{% load staticfiles %}
{% load thumbnail %}

{% block scripts %}

<!--[if lte IE 8]><script src="{% static 'photo/css/ie/html5shiv.js' %}"></script><![endif]-->
<script src="{% static 'photo/js/jquery.min.js' %}"></script>
<script src="{% static 'photo/js/skel.min.js' %}"></script>
<script src="{% static 'photo/js/jquery.scrolly.min.js' %}"></script>
<script src="{% static 'photo/js/lightbox.min.js' %}"></script>
<script src="{% static 'photo/js/init.js' %}"></script>

                  <script src="{% static 'photo/js/jquery.validationEngine-ru.js' %}"></script>
<script src="{% static 'photo/js/jquery.validationEngine.js' %}"></script>

<script>
      jQuery(document).ready(function(){
        // binds form submission and fields to the validation engine
        jQuery("#formID").validationEngine();
      });

      /**
      *
      * @param {jqObject} the field where the validation applies
      * @param {Array[String]} validation rules for this field
      * @param {int} rule index
      * @param {Map} form options
      * @return an error string if validation failed
      */
    </script>

    <link rel="stylesheet" type="text/css" href="{% static 'photo/css/validationEngine.jquery.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'photo/css/lightbox.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'photo/css/skel.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'photo/css/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'photo/css/style-desktop.css' %}" />

        <!--[if lte IE 8]><link rel="stylesheet" href="{% static 'photo/css/ie/v8.css' %}" /><![endif]-->
		<!--[if lte IE 9]><link rel="stylesheet" href="{% static 'photo/css/ie/v9.css' %}" /><![endif]-->

{% endblock %}

<head lang="en">
		<title>Фотограф Анастасия Травкина</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="Сайт семейного фотографа Анастасии Травкиной. Направления, в которых я работаю: свадебная съемка, пленер, семейная съемка, любовные истории, студийная съемка" />
		<meta name="keywords" content="фотография Тула Анастасия Травкина свадебная семейная студийная пленер фотосъемка  фото съемка" />
        <link rel="icon" href="{% static 'photo/images/favicon.ico' %}" type="image/x-icon">
        <link rel="shortcut icon" href="{% static 'photo/images/favicon.ico' %}" type="image/x-icon">
        <script src='https://www.google.com/recaptcha/api.js'></script>
	</head>
	<body>

        <noindex>
        <!--LiveInternet counter-->
        <script type="text/javascript"><!--
        new Image().src = "//counter.yadro.ru/hit?r"+
        escape(document.referrer)+((typeof(screen)=="undefined")?"":
        ";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
        screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
        ";"+Math.random();//--></script>
        <!--/LiveInternet-->
        </noindex>

		<!-- Nav -->
			<nav id="nav">
				<ul class="container">
                    <li><a href="{% url 'photo:index' %}">Главная</a></li>
					<li><a href="#portfolio">Портфолио</a></li>
					<li><a href="#contact">Обратная связь</a></li>
				</ul>
			</nav>

		<!-- Portfolio -->
			<div class="wrapper style3">
				<article id="portfolio">
					<header>
						<h2>{{ album.description }}</h2>
                        {% if not album.photo_set.all %}
                            <p>Здесь пока пусто, но мы это скоро исправим.</p>
                        {% endif %}
					</header>
					<div class="container">
                        <div class="row">

                            {% for photo in album.photo_set.all %}

							<div class="4u">

                                    {% thumbnail photo.image "384x269" crop="center" as thumb %}
                                        <a href="{{ photo.image.url }}" data-lightbox="gallery" data-title="{{ photo.title }}" class="image featured"><img src="{{ thumb.url }}" width="{{ thumb.width }}" height="{{ thumb.height }}" alt="" /></a>
									{% endthumbnail %}

							</div>
                            {% endfor %}
						</div>
					</div>
					<footer>
						{% if album.photo_set.all %}
                            <p>Вам понравились мои работы? Тогда свяжитесь со мной. </p>
                        {% endif %}
						<a href="#contact" class="button big scrolly">Написать письмо</a>
					</footer>
				</article>
			</div>

		<!-- Contact -->
			<div class="wrapper style4">
				<article id="contact" class="container 75%">
					<header>
						<h2>Напишите мне письмо.</h2>
						<p>Задавайте вопросы, я Вам обязательно отвечу.</p>
					</header>
					<div>
						<div class="row">
							<div class  ="12u">
								<form method="post" action="{% url 'photo:feedback' %}" id="formID">
                                    {% csrf_token %}
									<div>
										<div class="row">
											<div class="6u">
                                                {{ form.name }}
											</div>
											<div class="6u">
                                                {{ form.email }}
											</div>
										</div>
										<div class="row">
											<div class="12u">
                                                {{ form.subject }}
											</div>
										</div>
										<div class="row">
											<div class="12u">
                                                {{ form.message }}
											</div>
										</div>
										<div class="row">
                                            <div class="12u">
                                                <div class="g-recaptcha" style="width: 300px; margin: auto;" data-theme="dark" data-sitekey="6LeekwQTAAAAAKjKmCrLIbxLwtAdbdvQGb4srchd"></div>
                                            </div>
                                        </div>
										<div class="row 200%">
											<div class="12u">
												<ul class="actions">
													<li><input type="submit" class="submit" value="Отправить" /></li>
													<li><input type="reset" value="Очистить" class="alt" /></li>
												</ul>
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>
						<div class="row">
							<div class="12u">
								<hr />
								<h3>Ищите меня в социальных сетях</h3>
								<ul class="social">
									<li><a href="http://vk.com/travkina.anastasia_photo" class="icon fa-vk"><span class="label"></span></a></li>
                                    <li><a href="https://instagram.com/nastenka_kshk/" class="icon fa-instagram"><span></span></a></li>
                                    <li><a href="https://twitter.com/murkamur1995" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
									<li><a href="https://www.facebook.com/profile.php?id=100008995661742" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
									<!--
									<li><a href="#" class="icon fa-rss"><span>RSS</span></a></li>
									<li><a href="#" class="icon fa-instagram"><span>Instagram</span></a></li>
									<li><a href="#" class="icon fa-foursquare"><span>Foursquare</span></a></li>
									<li><a href="#" class="icon fa-skype"><span>Skype</span></a></li>
									<li><a href="#" class="icon fa-soundcloud"><span>Soundcloud</span></a></li>
									<li><a href="#" class="icon fa-youtube"><span>YouTube</span></a></li>
									<li><a href="#" class="icon fa-blogger"><span>Blogger</span></a></li>
									<li><a href="#" class="icon fa-flickr"><span>Flickr</span></a></li>
									<li><a href="#" class="icon fa-vimeo"><span>Vimeo</span></a></li>
									-->
								</ul>
								<hr />
							</div>
						</div>
					</div>
					<footer>
						<ul id="copyright">
							<li>&copy; 2015 Artyom Koshko. All rights reserved.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li><li>Photo: Anastasia Travkina<li>
						</ul>
					</footer>
				</article>
				        <noindex>
							<div>
                                <!--LiveInternet logo--><a href="//www.liveinternet.ru/click"
                                target="_blank" rel=”nofollow”><img src="//counter.yadro.ru/logo?50.3"
                                title="LiveInternet"
                                alt="" border="0" width="31" height="31"/></a><!--/LiveInternet-->
							</div>
						</noindex>
			</div>

	</body>
</html>